name = "pokemon-api-solidjs"
compatibility_date = "2025-06-04"

[assets]
directory = "./dist"

# Configuración para SPA (Single Page Application)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200 